### ISSUE TITLE
Extreme slowdown or complete game freeze.

### ISSUE THREAD

**Issue by ArchTeryx01** [klyte45/WriteEverywhere#5] opened 2022-11-17 11:42 UTC
**Describe the bug**
When WE is activated and my city loaded, the game slows to a crawl or freezes altogether.  FPS drops below 1 and I am often unable to even more the camera.  The only way to regain control is to force-quit the game, usually through Task Manager.

The bug is present with UU and VS also running, but running WE as the only Klyte mod also generates the bug.  It is very consistent, occurring whenever I load a city

[CompatibilityReport.txt](https://github.com/klyte45/WriteEverywhere/files/10031271/CompatibilityReport.txt)
[WE.log.txt](https://github.com/klyte45/WriteEverywhere/files/10031288/WE.log.txt)
[output_log.txt](https://github.com/klyte45/WriteEverywhere/files/10045738/output_log.txt) - Log with all three Klyte mods running (Vehicle Skins, Custom Data Mod and Write Everywhere)
[output_log2.txt](https://github.com/klyte45/WriteEverywhere/files/10045788/output_log2.txt) - Log with just WE active + my normal mods.

**Additional context**
In addition to the logs the compatibility report was also uploaded to give an idea of which mods were running at the time WE generated the bug.

**Comment by ArchTeryx01** [comment] 2022-11-19 01:26
My apologies. I have uploaded two new output_log.txt files, one with all three of your new mods running, one with only Write Everywhere running. (In both cases, all my other mods are also running).

**Comment by Kovoschiz** [comment] 2022-11-20 17:09
I can reproduce it again in this update. Partial re-open of #2 --- loading time lengthened by ~3.5 minutes, stuck at main thread `Update Render Group`. But now gameplay seems fine. No frame rate issue yet. 

With: 
https://github.com/Kovoschiz/kovoschiz.github.io/blob/main/1/_LOGS/WE.log.txt
https://raw.githubusercontent.com/Kovoschiz/kovoschiz.github.io/main/1/output_log.txt
https://kovoschiz.github.io/1/CompatibilityReport.html

Without: 
https://raw.githubusercontent.com/Kovoschiz/kovoschiz.github.io/main/0/output_log.txt
https://kovoschiz.github.io/0/CompatibilityReport.html

**Comment by klyte45** [comment] 2023-02-04 01:14
Well, I need a valid log with WE data to check this.
Since a the version is not the same anymore, closing this

**Closed by klyte45** 2023-02-04 01:14 UTC
Labels: question
